// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:ai_habits/models/base-object/base_object.dart';
import 'package:ai_habits/models/journal/journal.dart';
import 'package:ai_habits/models/user/user.dart';
import 'package:ai_habits/store/hive/journal/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BaseObjectAdapter());
    registerAdapter(JournalAdapter());
    registerAdapter(JournalAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BaseObjectAdapter());
    registerAdapter(JournalAdapter());
    registerAdapter(JournalAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserAdapter());
  }
}
