name: ai_habits
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
